services:
  postgres:
    image: postgres:15            # Официальный образ PostgreSQL
    container_name: postgres_snakewar   # Имя контейнера
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # Имя пользователя БД (берем из .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль (берем из .env)
      POSTGRES_DB: ${POSTGRES_DB}              # База данных, создаваемая при запуске (берем из .env)
    volumes:
      - pgdata:/var/lib/postgresql/data        # Хранилище данных
    ports:
      - "${POSTGRES_PORT:-5432}:5432"                # Проброс порта: хост:контейнер (хост берем из .env)

  python-service:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      - DATABASE_URL=postgresql+asyncpg://lone_shmul:zmeiki@localhost:5432/snakes
      - AUTH_PORT=${AUTH_SERVICE_PORT}
      - JWT_KEY=Shmul_pedik
      - GAME_SERVER_ADDRESS=${GAME_SERVER_ADDRESS}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}" #LOCALHOST - CONTAINER (:-8000 те дефолтное значение 8000)
    depends_on:
      - postgres
    networks:
      - app-network
    
  go-service:
    build:
      context: ./Game
      dockerfile: Dockerfile
    container_name: game_service
    environment:
      - GAME_PORT=${GAME_SERVICE_PORT}
    ports:
      - "${GAME_SERVICE_PORT}:${GAME_SERVICE_PORT}"
    networks:
      - app-network


volumes:
  pgdata:                         


networks:
  app-network:
    driver: bridge
